#!/bin/bash
set -o pipefail

function cmd_supports_json() {
    /usr/bin/docker $@ --help | grep -- '--format' > /dev/null
}

function stopall() {
    # stop all running docker containers
    docker ps |
        jq --raw-output .ID |
        xargs -n 1 --no-run-if-empty -P0 docker stop
}

function cleanall() {
    # remove any docker containers
    docker images |
        jq --raw-output .ID |
        xargs -n 1 --no-run-if-empty -P0 -- docker image rm --force
}

function have_jq() {
    jq --help > /dev/null 2>/dev/null
}

if cmd_supports_json $@
then
    WORKFILE=$(mktemp)
    if /usr/bin/docker $@ --format "{{json .}}" > $WORKFILE
    then
        if have_jq
        then
            cat $WORKFILE | jq .
        else
            cat $WORKFILE | python -c "
import json
import sys
for iline in sys.stdin:
    print json.dumps(json.loads(iline), indent=4, sort_keys=True)"
        fi
    fi
else
    case $1 in
        stopall)
            stopall
            ;;
        cleanall)
            cleanall
            ;;
        *)
            /usr/bin/docker $@
            ;;
    esac
fi
