#!/usr/bin/python
import argparse
import sys
from urllib import unquote_plus


def read_stdin_or_first_arg():
    if len(sys.argv) > 1:
        return sys.argv[1]
    else:
        return sys.stdin.read().strip()

    
def main():
    argparse.ArgumentParser(description='urldecode some text').parse_known_args()
    to_encode = read_stdin_or_first_arg()
    print unquote_plus(to_encode)

    
if "__main__" == __name__:
    main()
